#!/usr/bin/env node

const Sequelize = require('sequelize')
const models = require('../src/models')

const db = new Sequelize(process.argv[2])

models(db)

db.sync({ force: true })
  .then(() => db.close())
